// Generated by CodiumAI

describe('App', () => {

  // Renders the application section with the given content
  it('should render the application section with the given content', () => {
    // Arrange
    const className = "test-class";

    // Act
    const result = App({ className });

    // Assert
    expect(result).toMatchSnapshot();
  });

  // Animates the subtitle and title of the application section on scroll
  it('should animate the subtitle and title of the application section on scroll', () => {
    // Arrange
    const className = "test-class";

    // Act
    const result = App({ className });

    // Assert
    expect(result).toMatchSnapshot();
  });

  // Displays the image of the application section
  it('should display the image of the application section', () => {
    // Arrange
    const className = "test-class";

    // Act
    const result = App({ className });

    // Assert
    expect(result).toMatchSnapshot();
  });

  // appContent.heading.subTitle is undefined
  it('should handle undefined appContent.heading.subTitle', () => {
    // Arrange
    const className = "test-class";

    // Act
    const result = App({ className });

    // Assert
    expect(result).toMatchSnapshot();
  });

  // appContent.heading.title is undefined
  it('should handle undefined appContent.heading.title', () => {
    // Arrange
    const className = "test-class";

    // Act
    const result = App({ className });

    // Assert
    expect(result).toMatchSnapshot();
  });

  // appContent.content.title is undefined
  it('should handle undefined appContent.content.title', () => {
    // Arrange
    const className = "test-class";

    // Act
    const result = App({ className });

    // Assert
    expect(result).toMatchSnapshot();
  });
});
